"""create sentiment table

Revision ID: 1b5336dc47f5
Revises: b82538077eea
Create Date: 2026-08-04 14:54:25.420254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5336dc47f5'
down_revision: Union[str, Sequence[str], None] = 'b82538077eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sentiment_predictions', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sentiment_predictions', 'predicted_sentiment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_sentiment_predictions_id'), table_name='sentiment_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sentiment_predictions_id'), 'sentiment_predictions', ['id'], unique=False)
    op.alter_column('sentiment_predictions', 'predicted_sentiment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sentiment_predictions', 'input_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
